# Quick cheatsheet for Numpy

In [1]:
#First Let's Import the panda library
import numpy as np

In [2]:
mList = [9,8,7,6,5]

In [4]:
mList

[9, 8, 7, 6, 5]

In [5]:
# To convert list to array
mArr = np.array(mList)

In [6]:
type(mArr)

numpy.ndarray

In [7]:
mArr

array([9, 8, 7, 6, 5])

In [11]:
#To generate an array of numbers between a range
mArr = np.arange(10,50)
mArr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [12]:
#To generate an array with a specific 
mArr = np.arange(10,50,5)
mArr

array([10, 15, 20, 25, 30, 35, 40, 45])

In [13]:
#To generate a 2 dimensional array with 4 rows and 5 columns, with zero as value
mArr = np.zeros((4,5))
mArr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
#To generate a 2 dimensional array with 4 rows and 5 columns, with one as value
mArr = np.ones((4,5))
mArr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
#To generate random integer limit, the first argument is the 
#lower limit and the second one is upper limit
np.random.randint(10,50)

17

In [20]:
# Okay, now let's generate a 2 dimensional array with random numbers, add a third arguement with the
#size of the array
np.random.randint(10,50,(4,5))



array([[14, 28, 17, 31, 11],
       [42, 45, 20, 11, 18],
       [19, 40, 28, 29, 21],
       [19, 49, 42, 29, 15]])

In [22]:
# Say you want to generate linearily spaced number between a range
# First arguement is the lower limit, second one is upper limit, and the last one 
#is the number of numbers to be returned. 
np.linspace(10,50,50)



array([10.        , 10.81632653, 11.63265306, 12.44897959, 13.26530612,
       14.08163265, 14.89795918, 15.71428571, 16.53061224, 17.34693878,
       18.16326531, 18.97959184, 19.79591837, 20.6122449 , 21.42857143,
       22.24489796, 23.06122449, 23.87755102, 24.69387755, 25.51020408,
       26.32653061, 27.14285714, 27.95918367, 28.7755102 , 29.59183673,
       30.40816327, 31.2244898 , 32.04081633, 32.85714286, 33.67346939,
       34.48979592, 35.30612245, 36.12244898, 36.93877551, 37.75510204,
       38.57142857, 39.3877551 , 40.20408163, 41.02040816, 41.83673469,
       42.65306122, 43.46938776, 44.28571429, 45.10204082, 45.91836735,
       46.73469388, 47.55102041, 48.36734694, 49.18367347, 50.        ])

https://stackoverflow.com/questions/21494489/what-does-numpy-random-seed0-do

In [35]:
#np.random.seed(0) makes the random numbers predictable

np.random.seed(50)

In [37]:
mArr=np.random.randint(10,50,20)
mArr

array([16, 30, 41, 31, 10, 16, 29, 12, 25, 40, 45, 36, 12, 22, 42, 13, 12,
       20, 10, 39])

In [39]:
#Max, Min, Mean,
mArr.max()

45

In [40]:
mArr.min()

10

In [41]:
mArr.mean()

25.05

In [43]:
#argmax returns the position of the largest value. max returns the largest value.
# in our case number 45 is in the 10th position
mArr.argmax()

10

In [45]:
# To generate random numbers and form a matrix
mArr=np.random.randint(10,50,100).reshape(10,10)
mArr

array([[14, 21, 29, 24, 13, 38, 14, 37, 46, 17],
       [23, 31, 38, 31, 24, 23, 45, 16, 22, 10],
       [10, 18, 42, 24, 14, 42, 17, 46, 35, 21],
       [36, 42, 33, 48, 13, 38, 15, 38, 11, 45],
       [13, 10, 22, 47, 22, 42, 31, 24, 29, 26],
       [43, 29, 42, 14, 25, 28, 41, 32, 12, 15],
       [11, 43, 35, 20, 28, 18, 24, 27, 25, 38],
       [43, 33, 49, 32, 30, 38, 29, 29, 46, 15],
       [10, 49, 49, 37, 34, 12, 20, 19, 16, 47],
       [28, 47, 20, 47, 25, 23, 31, 17, 48, 10]])

In [49]:
# Let's check all the numbers in the matrix against a condition, quick
# and easy
mArr > 40

array([[False, False, False, False, False, False, False, False,  True,
        False],
       [False, False, False, False, False, False,  True, False, False,
        False],
       [False, False,  True, False, False,  True, False,  True, False,
        False],
       [False,  True, False,  True, False, False, False, False, False,
         True],
       [False, False, False,  True, False,  True, False, False, False,
        False],
       [ True, False,  True, False, False, False,  True, False, False,
        False],
       [False,  True, False, False, False, False, False, False, False,
        False],
       [ True, False,  True, False, False, False, False, False,  True,
        False],
       [False,  True,  True, False, False, False, False, False, False,
         True],
       [False,  True, False,  True, False, False, False, False,  True,
        False]])

In [51]:
# From the above matrix let's select all the numbers that are greater than 40
mArr[mArr > 40]

array([46, 45, 42, 42, 46, 42, 48, 45, 47, 42, 43, 42, 41, 43, 43, 49, 46,
       49, 49, 47, 47, 47, 48])